package:
  name: shift-python
  version: "0.0.1"

source:
  git_url: https://github.com/hanlonlab/shift-python.git

requirements:
  build:
    - python
    - shift-coreclient
  run:
    - python
    - shift-coreclient

test:
  imports:
    - shift

about:
  home: https://github.com/hanlonlab/shift-python
