package:
  name: shift-miscutils
  version: "1.3.0"

source:
  git_url: https://github.com/hanlonlab/shift-main.git

build:
  include_recipe: False

about:
  home: https://github.com/hanlonlab/shift-main
