package:
  name: shift-coreclient
  version: "1.1.0"

source:
  git_url: https://github.com/hanlonlab/shift-main.git

requirements:
  build:
    # - {{ compiler('cxx') }}
    - cmake
    - curl
    - quickfix
    - shift-miscutils
  run:
    - curl
    - quickfix
    - shift-miscutils

build:
  include_recipe: False

about:
  home: https://github.com/hanlonlab/shift-main
