package:
  name: quickfix
  version: "1.15.1"

source:
  git_url: https://github.com/quickfix/quickfix.git

build:
  include_recipe: False

requirements:
  build:
    # - {{ compiler('cxx') }}
    # - cmake
    - openssl
  run:
    - openssl

about:
  home: https://github.com/quickfix/quickfix
  license_file: LICENSE
